#!/bin/bash

#############################################
# commit and push
#############################################
while getopts m:r:b: option
do
 case "${option}"
 in
 m) MESSAGE=${OPTARG};;
 r) REPOSITORY=${OPTARG};;
 b) BRANCH=${OPTARG};;
 esac
done

if [ -z "${MESSAGE}" ] && [ -z "${DESTINATION}" ] && [ -z "${BRANCH}" ];
  then
    echo "Skipping commit and push."
    echo "Usage: ng_deploy -m \"my message\" -r \"heroku\" -b \"master\""
  else
    #-m and -d count as own parameters, therefore everything above 4 parameters
    # shall be rejected
    MORE_PARAMS=$5
    if [ -z "${MORE_PARAMS}" ];
      then
        echo "Skipping commit and push."
        echo "Usage: ng_deploy -m \"my message\" -r \"heroku\" -b \"master\""
      else
        git add .
        git commit -m "$MESSAGE"
        git push "$REPOSITORY" "$BRANCH"
    fi
fi
