#!/bin/bash

#############################################
# commit and push
#############################################
while getopts m:d: option
do
 case "${option}"
 in
 m) MESSAGE=${OPTARG};;
 d) DESTINATION=${OPTARG};;
 esac
done

if [ -z "${MESSAGE}" ];
  then
    echo "Skipping commit and push. Reason:"
    echo "  Commit Message is unset or set to the empty string"
  else
    if [ -z "${DESTINATION}" ];
      then
        echo "Skipping commit and push. Reason:"
        echo "  Destination is unset or set to the empty string"
      else
            #-m and -d count as own parameters, therefore everything above 4 parameters
            # shall be rejected
            MORE_PARAMS=$5
            if [ -z "${MORE_PARAMS}" ];
              then
                git add .
                git commit -m "$MESSAGE"
                git push "$DESTINATION"
              else
                echo "Skipping commit and push. Reason:"
                echo "  Too many parameters."
                echo "Usage: ng_deploy -m \"my message\" -d \"heroku master\""
            fi
    fi
fi
