#!/bin/bash

echo "=============== commit and push ==============="
while getopts m:r:b: option
do
 case "${option}"
 in
 m) MESSAGE=${OPTARG};;
 r) REPOSITORY=${OPTARG};;
 b) BRANCH=${OPTARG};;
 esac
done

if [ -z "${MESSAGE}" ];
  then
    echo "Commit message is mandatory parameter."
    echo "Usage: ng_deploy -m \"my message\" [-r \"heroku\" -b \"master\"]"
  else
    #-m and -d count as own parameters, therefore everything above 6 parameters
    # shall be rejected
    MORE_PARAMS=$7
    if [ -z "${MORE_PARAMS}" ];
      then
        if [ -z "${DESTINATION}" ] || [ -z "${BRANCH}" ];
          then
            REPOSITORY="heroku"
            BRANCH="master"
        fi
        echo "=============== ADDING & COMMITING ==============="
        echo "git add -A"
        git add -A
        echo "git commit -m $MESSAGE"
        git commit -m "$MESSAGE"
        echo "=============== PUSHING TO ==============="
        echo "=============== $REPOSITORY $BRANCH ==============="
        echo "git push $REPOSITORY $BRANCH"
        git push "$REPOSITORY" "$BRANCH"
      else
        echo "Too many parameters"
        echo "Usage: ng_deploy -m \"my message\" [-r \"heroku\" -b \"master\"]"
    fi
fi
echo "=============== ENDING: commit and push ==============="
