<?php

class ReturnValues {
    public static $AMAZON_QUERY_SHOULD_START = "AMAZON_QUERY_SHOULD_START";
    public static $AMAZON_QUERY_SHOULD_CONTINUE = "AMAZON_QUERY_SHOULD_CONTINUE";
    public static $AMAZON_WAIT_FOR_PREVIOUS_QUERY_TO_FINISH = "AMAZON_WAIT_FOR_PREVIOUS_QUERY_TO_FINISH";

    public static $IMDB_QUERY_SHOULD_START = "IMDB_QUERY_SHOULD_START";
    public static $IMDB_QUERY_SHOULD_CONTINUE = "IMDB_QUERY_SHOULD_CONTINUE";

    public static $ALL_UP_TO_DATE = "ALL_UP_TO_DATE";

    public static $UNDEFINED = "UNDEFINED";
}